pipeline {
    agent any
    stages{
        stage("printEnv"){
            steps {
                sh "printenv"
                cleanWs()
            }
        }
        stage("Build Source Code"){
            steps {

                dir('sonarqube-scanner-maven/maven-basic') {
                    sh "mvn install"
                    sh "ls -lrt target/"
                    sh "mv target/*.jar target/sonarscanner-maven-basic-1.0-SNAPSHOT-${BUILD_NUMBER}.jar"
                    sh "ls -lrt target/"
                }
            }
        }
        stage("Run Unit-Tests"){
            steps {
                dir('sonarqube-scanner-maven/maven-basic') {
                    sh "mvn test"
                }
            }
        }
        // stage('Sonarqube Analysis') {
        //     environment {
        //       def scannerHome = tool 'SonarQubeScanner'
        //     }
        //     steps {  
        //         withSonarQubeEnv('sonarserver') {
        //             dir('sonarqube-scanner-maven/maven-basic') {
        //                 sh "/opt/sonar/bin/sonar-scanner"
        //                 //sh "${scannerHome}/bin/sonar-scanner"
        //             }
        //         }
        //         sleep time: 30000, unit: 'MILLISECONDS'
        //         script {
        //                 def qg = waitForQualityGate()
        //                 if (qg.status != 'OK') {
        //                     error "Pipeline aborted due to quality gate failure: ${qg.status}"
        //                 }
        //         }
        //     }
        // }

        // stage("Upload Artifacts"){
        //     steps{
        //         dir('sonarqube-scanner-maven/maven-basic'){
        //             rtUpload (
        //                 serverId: 'jfrog-server',
        //                 spec: '''{
        //                     "files": [
        //                         {
        //                         "pattern": "target/*.jar",
        //                         "target": "dummyrepo/froggy-files/"
        //                         }
        //                     ]
        //                 }''',
        //             )

        //         }
                    
        //     }
        // }            

        // stage("Deploy - DEV"){
        //     steps{
        //         echo "Running Deployment on Dev"
        //     }
        // }  
        
        // stage("Deploy - UAT"){
        //     steps{
        //         echo "Running Deployment on UAT"
        //     }
        // }
        // stage("Deploy - PRD"){
        //     steps{
        //         echo "Running Deployment on PRD"
        //     }
        // } 
    
    }
}
